name: build

on:
  pull_request:
    branches: [ master ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install nightly
      uses: actions-rs/toolchain@v1
      with:
        toolchain: nightly-2021-05-20
        target: wasm32-unknown-unknown --toolchain nightly-2021-05-20
        override: true
        components: rustfmt, clippy
    - name: Build
      run: cargo +nightly-2021-05-20 build --verbose
    - name: Run tests
      run: cargo +nightly-2021-05-20 test --verbose
